/********************************************************************
* RBExperimentDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error RBExperimentDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableRBExperimentDict();
extern void G__cpp_setup_inheritanceRBExperimentDict();
extern void G__cpp_setup_typetableRBExperimentDict();
extern void G__cpp_setup_memvarRBExperimentDict();
extern void G__cpp_setup_globalRBExperimentDict();
extern void G__cpp_setup_memfuncRBExperimentDict();
extern void G__cpp_setup_funcRBExperimentDict();
extern void G__set_cpp_environmentRBExperimentDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "RBExperiment.h"
#include "RBRingItem.h"
#include "RBRingStateChangeItem.h"
#include "RBNSCLBufferHeader.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__RBExperimentDictLN_TClass;
extern G__linked_taginfo G__RBExperimentDictLN_TBuffer;
extern G__linked_taginfo G__RBExperimentDictLN_TMemberInspector;
extern G__linked_taginfo G__RBExperimentDictLN_TObject;
extern G__linked_taginfo G__RBExperimentDictLN_TNamed;
extern G__linked_taginfo G__RBExperimentDictLN_TString;
extern G__linked_taginfo G__RBExperimentDictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR;
extern G__linked_taginfo G__RBExperimentDictLN_basic_ifstreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__RBExperimentDictLN_string;
extern G__linked_taginfo G__RBExperimentDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__RBExperimentDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__RBExperimentDictLN_TList;
extern G__linked_taginfo G__RBExperimentDictLN_TObjArray;
extern G__linked_taginfo G__RBExperimentDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__RBExperimentDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__RBExperimentDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__RBExperimentDictLN_TFile;
extern G__linked_taginfo G__RBExperimentDictLN_TFolder;
extern G__linked_taginfo G__RBExperimentDictLN_TTree;
extern G__linked_taginfo G__RBExperimentDictLN_TBranch;
extern G__linked_taginfo G__RBExperimentDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__RBExperimentDictLN_RBNSCLBufferHeader;
extern G__linked_taginfo G__RBExperimentDictLN_RBRingItem;
extern G__linked_taginfo G__RBExperimentDictLN_RBRingStateChangeItem;
extern G__linked_taginfo G__RBExperimentDictLN_RBElectronics;
extern G__linked_taginfo G__RBExperimentDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__RBExperimentDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__RBExperimentDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__RBExperimentDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__RBExperimentDictLN_RBExperiment;

/* STUB derived class for protected member access */
