/********************************************************************
* RBElectronicsDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error RBElectronicsDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableRBElectronicsDict();
extern void G__cpp_setup_inheritanceRBElectronicsDict();
extern void G__cpp_setup_typetableRBElectronicsDict();
extern void G__cpp_setup_memvarRBElectronicsDict();
extern void G__cpp_setup_globalRBElectronicsDict();
extern void G__cpp_setup_memfuncRBElectronicsDict();
extern void G__cpp_setup_funcRBElectronicsDict();
extern void G__set_cpp_environmentRBElectronicsDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "RBElectronics.h"
#include "RBPedestalManager.h"
#include "RBHINPHit.h"
#include "RBSisTimestampUnpacker.h"
#include "RBHINPUnpacker.h"
#include "RBCCUSBPacket.h"
#include "RBCAEN7xxUnpacker.h"
#include "RBUSBStackMarker.h"
#include "RBTimestamp.h"
#include "RBPh7xxUnpacker.h"
#include "RBUSBStack.h"
#include "RBModuleUnpacker.h"
#include "RBCAEN1x90Unpacker.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__RBElectronicsDictLN_TClass;
extern G__linked_taginfo G__RBElectronicsDictLN_TBuffer;
extern G__linked_taginfo G__RBElectronicsDictLN_TMemberInspector;
extern G__linked_taginfo G__RBElectronicsDictLN_TObject;
extern G__linked_taginfo G__RBElectronicsDictLN_TString;
extern G__linked_taginfo G__RBElectronicsDictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR;
extern G__linked_taginfo G__RBElectronicsDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__RBElectronicsDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__RBElectronicsDictLN_TList;
extern G__linked_taginfo G__RBElectronicsDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__RBElectronicsDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__RBElectronicsDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__RBElectronicsDictLN_TTree;
extern G__linked_taginfo G__RBElectronicsDictLN_TBranch;
extern G__linked_taginfo G__RBElectronicsDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__RBElectronicsDictLN_RBElectronics;
extern G__linked_taginfo G__RBElectronicsDictLN_RBHINPHit;
extern G__linked_taginfo G__RBElectronicsDictLN_RBModuleUnpacker;
extern G__linked_taginfo G__RBElectronicsDictLN_RBSisTimestampUnpacker;
extern G__linked_taginfo G__RBElectronicsDictLN_RBHINPUnpacker;
extern G__linked_taginfo G__RBElectronicsDictLN_RBCCUSBPacket;
extern G__linked_taginfo G__RBElectronicsDictLN_RBCAEN7xxUnpacker;
extern G__linked_taginfo G__RBElectronicsDictLN_RBUSBStackMarker;
extern G__linked_taginfo G__RBElectronicsDictLN_RBTimestamp;
extern G__linked_taginfo G__RBElectronicsDictLN_RBPh7xxUnpacker;
extern G__linked_taginfo G__RBElectronicsDictLN_RBUSBStack;
extern G__linked_taginfo G__RBElectronicsDictLN_RBUSBStackcLcL_StackInfo;
extern G__linked_taginfo G__RBElectronicsDictLN_TRandom3;
extern G__linked_taginfo G__RBElectronicsDictLN_RBCAEN1x90Unpacker;

/* STUB derived class for protected member access */
