/********************************************************************
* RBSetupDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error RBSetupDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableRBSetupDict();
extern void G__cpp_setup_inheritanceRBSetupDict();
extern void G__cpp_setup_typetableRBSetupDict();
extern void G__cpp_setup_memvarRBSetupDict();
extern void G__cpp_setup_globalRBSetupDict();
extern void G__cpp_setup_memfuncRBSetupDict();
extern void G__cpp_setup_funcRBSetupDict();
extern void G__set_cpp_environmentRBSetupDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "RBSetup.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__RBSetupDictLN_TClass;
extern G__linked_taginfo G__RBSetupDictLN_TBuffer;
extern G__linked_taginfo G__RBSetupDictLN_TMemberInspector;
extern G__linked_taginfo G__RBSetupDictLN_TObject;
extern G__linked_taginfo G__RBSetupDictLN_TNamed;
extern G__linked_taginfo G__RBSetupDictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR;
extern G__linked_taginfo G__RBSetupDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__RBSetupDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__RBSetupDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__RBSetupDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__RBSetupDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__RBSetupDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__RBSetupDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__RBSetupDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__RBSetupDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__RBSetupDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__RBSetupDictLN_RBExperiment;
extern G__linked_taginfo G__RBSetupDictLN_RBSetup;

/* STUB derived class for protected member access */
