# Run clang-format
name: Clang-format

on: [push, pull_request]

jobs:
  checkout-and-check-formatting:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run clang-format
      uses: DoozyX/clang-format-lint-action@v0.11
      # These are optional (defaults displayed)
      with:   
        source: '.'
        exclude: './lib'
        extensions: 'h,cpp,cxx'
        clangFormatVersion: 11
        inplace: true
    - uses: EndBug/add-and-commit@v7
      with:
        default_author: github_actions
        message: 'Committing clang-format changes'
